import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "kazuki19992.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={"flex h-screen w-screen bg-gray-50 text-gray-800 dark:bg-gray-950 dark:text-gray-100"}>
        <div className=" sticky top-0 hidden w-64 overflow-hidden border lg:block">
          a
        </div>
        <div className="h-full grow flex-col">
          <div className="h-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
