import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "kazuki19992.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={"flex"}>
        <div className=" sticky top-0 hidden w-64 overflow-hidden border lg:block">
          a
        </div>
        <div className="grow">
          <div className="fixed h-16 w-full border"></div>
          {children}
        </div>
      </body>
    </html>
  );
}
